// <auto-generated />
namespace Books.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class quotesandimages : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(quotesandimages));
        
        string IMigrationMetadata.Id
        {
            get { return "201612161105132_quotes and images"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
